[package]
name = "privacy_transaction"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"
sha2 = "0.9.8"

[dependencies.secp256k1]
version = "0.20.2"
features = ["rand"]